# Лабораторная работа №4
## Изучение библиотек для обработки и визуализации данных

### Цели работы:
1. Познакомиться c библиотеками Python NumPy, Pandas и Matplotlib;
2. Разобраться с принципами работы в среде Jupyter Notebook на основе сервиса Google Colab;
3. Получить навыки выполнения векторных вычислений с использованием библиотеки NumPy;
4. Получить навыки анализа, обработки и визуализации датасетов с применением библиотек Pandas и Matplotlib.

### Задание
Пусть $\mathcal{N}(a, σ^2)$ – нормальное распределение с математическим ожиданием $a$ и дисперсией $σ^2$, 
$\mathbb{I}[β(x)] = 
\begin{dcases}
    1, & \text{if}\;β(x) = True \\
    0, & \text{if}\;β(x) = False
\end{dcases}$ – индикаторная функция от некоторого предиката $β(x)$, 
$\Vert\mathbf{u}\Vert_{p}=\sqrt[p]{\vert\mathbf{u}\vert^p}$ – $L_p$-норма вектора $\mathbf{u}$,
$\odot$ – поэлементное произведение матриц / векторов,
$\text{Tr}\;\mathbf{A}$ – след матрицы $\mathbf{A}$.
Требуется с помощью библиотеки Python NumPy создать следующие матрицы и векторы:

$\begin{equation}
    \notag
    \mathbf{M} =
    \begin{pmatrix}
        3 & 2 & 2 & 2 & \ldots & 2 \\
        2 & 5 & 2 & 2 & \ldots & 2 \\
        2 & 2 & 7 & 2 & \ldots & 2 \\
        \vdots & \vdots & \vdots & \vdots & \ddots & \vdots \\
        2 & 2 & 2 & 2 & \ldots & 171
    \end{pmatrix}, \mathbf{M} \in \N^{85\times85},
\end{equation}$

$\begin{equation}
    \notag
    \mathbf{N} =
    \begin{pmatrix}
        4 & 4 & 5 & 4 & 4 & 5 & 4 & \ldots \\
        4 & 7 & 4 & 7 & 4 & 7 & 4 & \ldots \\
        4 & 4 & 5 & 4 & 4 & 5 & 4 & \ldots \\
        \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \ddots & \vdots \\
        \ldots & \ldots & \ldots & \ldots & \ldots & \ldots & \ldots & \ldots
    \end{pmatrix}, \mathbf{N} \in \N^{85\times85},
\end{equation}$

$\begin{equation}
    \notag
    \mathbf{p} = \{1 + p_i : p_i \thicksim \mathcal{N}(2,4)\}_{i=0}^{84}\;,
\end{equation}$

$\begin{equation}
    \notag
    \mathbf{q}^T = \{\mathbf{N}_{24,j} \odot \mathbf{N}_{71,j}\}_{j=0}^{84}\;.
\end{equation}$

В соответствии с номером индивидуального варианта (12) требуется вычислить значения нижеприведенных выражений. ***При выполнении задания циклы использовать запрещено!***

2. 
$\begin{equation}
    \notag
    \mathbf{f} = 4 \; \mathbf{N}_{k^*,59} : k^*=\argmax_{k \in [0..84]}(\mathbf{q}_k^2)
\end{equation},
\quad
\begin{equation}
    \notag
    \mathbf{g} = \Sigma_{i=24}^{69} П_{j=13}^{27}(7 \cdot 10^{-6} (\mathbf{M}\mathbf{p})\mathbf{q}^T)_{ij}^2
\end{equation}.
$  

### Содержание <a class="anchor" id="content"></a>
1. [Импорт библиотек и инициализация переменных](#1);
2. [Формирование матриц $\mathbf{M}$ и $\mathbf{N}$](#2);
3. [Формирование векторов $\mathbf{p}$ и $\mathbf{q}^T$](#3);
4. [Вычисление значения функции $\mathbf{f}$](#4);
5. [Вычисление значения функции $\mathbf{g}$](#5).

#### Импорт библиотек и инициализация переменных <a class="anchor" id="1"></a>

In [387]:
import numpy as np

In [388]:
m_rows = 85
m_cols = 85

n_rows = 85
n_cols = 85

p_size = 85
q_size = 85

mean = 2
dispersion = 4
std = np.sqrt(dispersion)

#### Формирование матриц $\mathbf{M}$ и $\mathbf{N}$ <a class="anchor" id="2"></a>

Сформируем матрицу $\mathbf{M}$

In [389]:
m = np.full(
    shape=(m_rows, m_cols),
    fill_value=2,
    dtype=int
)

np.fill_diagonal(m, np.arange(3, 172, 2))

m

array([[  3,   2,   2, ...,   2,   2,   2],
       [  2,   5,   2, ...,   2,   2,   2],
       [  2,   2,   7, ...,   2,   2,   2],
       ...,
       [  2,   2,   2, ..., 167,   2,   2],
       [  2,   2,   2, ...,   2, 169,   2],
       [  2,   2,   2, ...,   2,   2, 171]])

Сформируем матрицу $\mathbf{N}$

In [390]:
n = np.full(
    shape=(n_rows, n_cols),
    fill_value=4,
    dtype=int
)

n[::2,2::3] = 5
n[1::2,1::2] = 7

n

array([[4, 4, 5, ..., 4, 5, 4],
       [4, 7, 4, ..., 4, 7, 4],
       [4, 4, 5, ..., 4, 5, 4],
       ...,
       [4, 4, 5, ..., 4, 5, 4],
       [4, 7, 4, ..., 4, 7, 4],
       [4, 4, 5, ..., 4, 5, 4]])

#### Формирование векторов $\mathbf{p}$ и $\mathbf{q}^T$ <a class="anchor" id="3"></a>

Сформируем вектор-столбец $\mathbf{p}$

In [391]:
p = np.array([np.random.normal(mean, std, p_size) + 1]).T
p

array([[ 5.35391488],
       [ 1.78666463],
       [ 0.79757993],
       [ 1.64360122],
       [ 3.13455079],
       [ 1.54869511],
       [ 4.04285118],
       [ 3.90492741],
       [ 1.93490013],
       [-0.49569309],
       [ 3.71135229],
       [ 3.34903059],
       [ 2.25155312],
       [ 0.56743226],
       [ 4.05266046],
       [ 0.47357199],
       [ 3.56035911],
       [ 2.8452191 ],
       [ 5.38490679],
       [-0.52156013],
       [ 3.26510624],
       [ 2.36938663],
       [-0.67693034],
       [ 5.78108693],
       [ 0.28698154],
       [ 6.28697952],
       [ 0.45312486],
       [ 3.28970035],
       [ 6.53232055],
       [ 1.56781976],
       [ 1.31288651],
       [ 1.94939423],
       [-0.19180344],
       [ 6.71209905],
       [ 3.10793131],
       [ 2.30173802],
       [ 2.27070785],
       [ 2.25341948],
       [ 3.26046391],
       [ 4.02284497],
       [-1.78585931],
       [ 3.38012352],
       [ 3.75072252],
       [ 4.28350408],
       [ 3.13294849],
       [ 2

Сформируем вектор-строку $\mathbf{q}^T$

In [392]:
q = np.array([n[24] * n[71]])
q

array([[16, 28, 20, 28, 16, 35, 16, 28, 20, 28, 16, 35, 16, 28, 20, 28,
        16, 35, 16, 28, 20, 28, 16, 35, 16, 28, 20, 28, 16, 35, 16, 28,
        20, 28, 16, 35, 16, 28, 20, 28, 16, 35, 16, 28, 20, 28, 16, 35,
        16, 28, 20, 28, 16, 35, 16, 28, 20, 28, 16, 35, 16, 28, 20, 28,
        16, 35, 16, 28, 20, 28, 16, 35, 16, 28, 20, 28, 16, 35, 16, 28,
        20, 28, 16, 35, 16]])

#### Вычисление значения функции $\mathbf{f}$ <a class="anchor" id="4"></a>

In [393]:
q_square = q ** 2
q_square

array([[ 256,  784,  400,  784,  256, 1225,  256,  784,  400,  784,  256,
        1225,  256,  784,  400,  784,  256, 1225,  256,  784,  400,  784,
         256, 1225,  256,  784,  400,  784,  256, 1225,  256,  784,  400,
         784,  256, 1225,  256,  784,  400,  784,  256, 1225,  256,  784,
         400,  784,  256, 1225,  256,  784,  400,  784,  256, 1225,  256,
         784,  400,  784,  256, 1225,  256,  784,  400,  784,  256, 1225,
         256,  784,  400,  784,  256, 1225,  256,  784,  400,  784,  256,
        1225,  256,  784,  400,  784,  256, 1225,  256]])

In [394]:
q_square_argmax = q_square.argmax()
q_square_argmax

5

In [395]:
f = 4 * n[q_square_argmax, 59]
f

28

#### Вычисление значения функции $\mathbf{g}$ <a class="anchor" id="5"></a>

In [396]:
m_dot_p = m.dot(p)
print(m_dot_p.shape)
print(m_dot_p)

(85, 1)
[[ 522.63753033]
 [ 522.64360936]
 [ 521.27151508]
 [ 528.78882397]
 [ 545.49457258]
 [ 534.31926164]
 [ 569.84068075]
 [ 575.85752663]
 [ 550.17691765]
 [ 507.86544681]
 [ 595.2220135 ]
 [ 594.31131905]
 [ 573.5724435 ]
 [ 532.60428658]
 [ 634.81076894]
 [ 531.964347  ]
 [ 634.77546609]
 [ 616.86628379]
 [ 716.52516674]
 [ 496.94277023]
 [ 651.15297124]
 [ 619.16724063]
 [ 486.82174993]
 [ 788.99470133]
 [ 531.34571096]
 [ 837.91957087]
 [ 541.299233  ]
 [ 698.21713453]
 [ 889.62588693]
 [ 609.78498137]
 [ 597.36969257]
 [ 640.09545171]
 [ 504.81639184]
 [ 966.99425149]
 [ 731.73087618]
 [ 680.70701514]
 [ 683.04528884]
 [ 686.29007625]
 [ 768.33933634]
 [ 835.08836808]
 [ 372.62901169]
 [ 797.83386748]
 [ 836.09502973]
 [ 889.94847028]
 [ 796.11603144]
 [ 777.14694956]
 [ 826.61724126]
 [ 697.56669579]
 [ 595.82030603]
 [ 934.0153659 ]
 [ 872.29298749]
 [1143.55691033]
 [ 959.97388486]
 [ 931.02849509]
 [ 779.91958495]
 [1068.69410093]
 [ 456.46506417]
 [ 608.27527157]
 [ 754

In [397]:
m_dot_p_mul_q = m_dot_p * q
print(m_dot_p_mul_q.shape)
print(m_dot_p_mul_q)

(85, 85)
[[ 8362.20048531 14633.8508493  10452.75060664 ...  8362.20048531
  18292.31356163  8362.20048531]
 [ 8362.29774971 14634.02106199 10452.87218714 ...  8362.29774971
  18292.52632749  8362.29774971]
 [ 8340.34424136 14595.60242237 10425.4303017  ...  8340.34424136
  18244.50302797  8340.34424136]
 ...
 [23707.1960426  41487.59307455 29633.99505325 ... 23707.1960426
  51859.49134319 23707.1960426 ]
 [30374.75540162 53155.82195284 37968.44425203 ... 30374.75540162
  66444.77744105 30374.75540162]
 [22221.74025793 38888.04545137 27777.17532241 ... 22221.74025793
  48610.05681422 22221.74025793]]


In [398]:
m_dot_p_mul_q_mul_constant = m_dot_p_mul_q * 7e-6
m_dot_p_mul_q_mul_constant

array([[0.0585354 , 0.10243696, 0.07316925, ..., 0.0585354 , 0.12804619,
        0.0585354 ],
       [0.05853608, 0.10243815, 0.07317011, ..., 0.05853608, 0.12804768,
        0.05853608],
       [0.05838241, 0.10216922, 0.07297801, ..., 0.05838241, 0.12771152,
        0.05838241],
       ...,
       [0.16595037, 0.29041315, 0.20743797, ..., 0.16595037, 0.36301644,
        0.16595037],
       [0.21262329, 0.37209075, 0.26577911, ..., 0.21262329, 0.46511344,
        0.21262329],
       [0.15555218, 0.27221632, 0.19444023, ..., 0.15555218, 0.3402704 ,
        0.15555218]])

In [399]:
m_dot_p_mul_q_mul_constant_square = m_dot_p_mul_q_mul_constant ** 2
m_dot_p_mul_q_mul_constant_square

array([[0.00342639, 0.01049333, 0.00535374, ..., 0.00342639, 0.01639583,
        0.00342639],
       [0.00342647, 0.01049357, 0.00535386, ..., 0.00342647, 0.01639621,
        0.00342647],
       [0.00340851, 0.01043855, 0.00532579, ..., 0.00340851, 0.01631023,
        0.00340851],
       ...,
       [0.02753953, 0.0843398 , 0.04303051, ..., 0.02753953, 0.13178094,
        0.02753953],
       [0.04520866, 0.13845153, 0.07063854, ..., 0.04520866, 0.21633051,
        0.04520866],
       [0.02419648, 0.07410172, 0.037807  , ..., 0.02419648, 0.11578394,
        0.02419648]])

In [400]:
submatrix = m_dot_p_mul_q_mul_constant_square[24:69,13:27]
print(submatrix.shape)
print(submatrix)

(45, 14)
[[0.01084592 0.00553363 0.01084592 0.00354153 0.01694675 0.00354153
  0.01084592 0.00553363 0.01084592 0.00354153 0.01694675 0.00354153
  0.01084592 0.00553363]
 [0.02697223 0.01376134 0.02697223 0.00880726 0.04214411 0.00880726
  0.02697223 0.01376134 0.02697223 0.00880726 0.04214411 0.00880726
  0.02697223 0.01376134]
 [0.01125607 0.0057429  0.01125607 0.00367545 0.01758762 0.00367545
  0.01125607 0.0057429  0.01125607 0.00367545 0.01758762 0.00367545
  0.01125607 0.0057429 ]
 [0.01872808 0.00955514 0.01872808 0.00611529 0.02926262 0.00611529
  0.01872808 0.00955514 0.01872808 0.00611529 0.02926262 0.00611529
  0.01872808 0.00955514]
 [0.03040374 0.01551211 0.03040374 0.00992775 0.04750584 0.00992775
  0.03040374 0.01551211 0.03040374 0.00992775 0.04750584 0.00992775
  0.03040374 0.01551211]
 [0.01428452 0.00728802 0.01428452 0.00466433 0.02231956 0.00466433
  0.01428452 0.00728802 0.01428452 0.00466433 0.02231956 0.00466433
  0.01428452 0.00728802]
 [0.01370877 0.00699427 0

In [401]:
submatrix_row_elements_mul = submatrix.prod(axis=1)
print(submatrix_row_elements_mul.shape)
print(submatrix_row_elements_mul)

(45,)
[1.14894296e-30 3.97560110e-25 1.93190148e-30 2.40697463e-27
 2.12591050e-24 5.42857337e-29 3.05173365e-29 2.11149570e-28
 2.73825571e-31 2.19586902e-23 8.94491284e-27 1.18201717e-27
 1.30113828e-27 1.48577682e-27 3.50932309e-26 3.61614312e-25
 5.56524203e-35 1.00759626e-25 3.74020507e-25 2.14760077e-24
 9.48583990e-26 4.82864806e-26 2.71808046e-25 2.34497438e-27
 2.83769590e-29 8.31093788e-24 1.22541761e-24 2.40411567e-21
 1.79061067e-23 7.59802462e-24 5.33497737e-26 3.61104571e-22
 1.63361113e-32 5.06456282e-29 2.13621051e-26 7.73557877e-23
 2.25118018e-20 8.64739682e-26 1.76249188e-27 1.24803826e-20
 3.76468630e-21 2.14592934e-21 4.38243615e-25 6.05992791e-20
 2.14378615e-19]


In [402]:
np.sum(submatrix_row_elements_mul)

3.187868457649001e-19

### Выводы
В ходе данного задания в лабораторной работе была изучена библиотека NumPy, были получены навыки выполнения векторных вычислений с использованием вышеназванной библиотеки и найдены значения заданных выражений.