# Лабораторная работа №4
## Изучение библиотек для обработки и визуализации данных

### Цели работы:
1. Познакомиться c библиотеками Python NumPy, Pandas и Matplotlib;
2. Разобраться с принципами работы в среде Jupyter Notebook на основе сервиса Google Colab;
3. Получить навыки выполнения векторных вычислений с использованием библиотеки NumPy;
4. Получить навыки анализа, обработки и визуализации датасетов с применением библиотек Pandas и Matplotlib.

### Задание
Пусть $\mathcal{N}(a, σ^2)$ – нормальное распределение с математическим ожиданием $a$ и дисперсией $σ^2$, 
$\mathbb{I}[β(x)] = 
\begin{dcases}
    1, & \text{if}\;β(x) = True \\
    0, & \text{if}\;β(x) = False
\end{dcases}$ – индикаторная функция от некоторого предиката $β(x)$, 
$\Vert\mathbf{u}\Vert_{p}=\sqrt[p]{\vert\mathbf{u}\vert^p}$ – $L_p$-норма вектора $\mathbf{u}$,
$\odot$ – поэлементное произведение матриц / векторов,
$\text{Tr}\;\mathbf{A}$ – след матрицы $\mathbf{A}$.
Требуется с помощью библиотеки Python NumPy создать следующие матрицы и векторы:

$\begin{equation}
    \notag
    \mathbf{M} =
    \begin{pmatrix}
        3 & 2 & 2 & 2 & \ldots & 2 \\
        2 & 5 & 2 & 2 & \ldots & 2 \\
        2 & 2 & 7 & 2 & \ldots & 2 \\
        \vdots & \vdots & \vdots & \vdots & \ddots & \vdots \\
        2 & 2 & 2 & 2 & \ldots & 171
    \end{pmatrix}, \mathbf{M} \in \N^{85\times85},
\end{equation}$

$\begin{equation}
    \notag
    \mathbf{N} =
    \begin{pmatrix}
        4 & 4 & 5 & 4 & 4 & 5 & 4 & \ldots \\
        4 & 7 & 4 & 7 & 4 & 7 & 4 & \ldots \\
        4 & 4 & 5 & 4 & 4 & 5 & 4 & \ldots \\
        \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \ddots & \vdots \\
        \ldots & \ldots & \ldots & \ldots & \ldots & \ldots & \ldots & \ldots
    \end{pmatrix}, \mathbf{N} \in \N^{85\times85},
\end{equation}$

$\begin{equation}
    \notag
    \mathbf{p} = \{1 + p_i : p_i \thicksim \mathcal{N}(2,4)\}_{i=0}^{84}\;,
\end{equation}$

$\begin{equation}
    \notag
    \mathbf{q}^T = \{\mathbf{N}_{24,j} \odot \mathbf{N}_{71,j}\}_{j=0}^{84}\;.
\end{equation}$

В соответствии с номером индивидуального варианта (12) требуется вычислить значения нижеприведенных выражений. ***При выполнении задания циклы использовать запрещено!***

2. 
$\begin{equation}
    \notag
    \mathbf{f} = 4 \; \mathbf{N}_{k^*,59} : k^*=\argmax_{k \in [0..84]}(\mathbf{q}_k^2)
\end{equation},
\quad
\begin{equation}
    \notag
    \mathbf{g} = \Sigma_{i=24}^{69} П_{j=13}^{27}(7 \cdot 10^{-6} (\mathbf{M}\mathbf{p})\mathbf{q}^T)_{ij}^2
\end{equation}.
$  

### Содержание <a class="anchor" id="content"></a>
1. [Импорт библиотек и инициализация переменных](#1);
2. [Формирование матриц $\mathbf{M}$ и $\mathbf{N}$](#2);
3. [Формирование векторов $\mathbf{p}$ и $\mathbf{q}^T$](#3);
4. [Вычисление значения функции $\mathbf{f}$](#4);
5. [Вычисление значения функции $\mathbf{g}$](#5).

#### Импорт библиотек и инициализация переменных <a class="anchor" id="1"></a>

In [35]:
import numpy as np

In [36]:
m_rows = 85
m_cols = 85

n_rows = 85
n_cols = 85

p_size = 85
q_size = 85

mean = 2
dispersion = 4
std = np.sqrt(dispersion)

#### Формирование матриц $\mathbf{M}$ и $\mathbf{N}$ <a class="anchor" id="2"></a>

Сформируем матрицу $\mathbf{M}$

In [37]:
m = np.full(
    shape=(m_rows, m_cols),
    fill_value=2,
    dtype=int
)

np.fill_diagonal(m, np.arange(3, 172, 2))

m

array([[  3,   2,   2, ...,   2,   2,   2],
       [  2,   5,   2, ...,   2,   2,   2],
       [  2,   2,   7, ...,   2,   2,   2],
       ...,
       [  2,   2,   2, ..., 167,   2,   2],
       [  2,   2,   2, ...,   2, 169,   2],
       [  2,   2,   2, ...,   2,   2, 171]])

Сформируем матрицу $\mathbf{N}$

In [38]:
n = np.full(
    shape=(n_rows, n_cols),
    fill_value=4,
    dtype=int
)

n[::2,2::3] = 5
n[1::2,1::2] = 7

n

array([[4, 4, 5, ..., 4, 5, 4],
       [4, 7, 4, ..., 4, 7, 4],
       [4, 4, 5, ..., 4, 5, 4],
       ...,
       [4, 4, 5, ..., 4, 5, 4],
       [4, 7, 4, ..., 4, 7, 4],
       [4, 4, 5, ..., 4, 5, 4]])

#### Формирование векторов $\mathbf{p}$ и $\mathbf{q}^T$ <a class="anchor" id="3"></a>

Сформируем вектор-столбец $\mathbf{p}$

In [39]:
p = np.array([np.random.normal(mean, std, p_size) + 1]).T
p

array([[ 1.90731157],
       [ 5.27588694],
       [ 4.90500677],
       [ 0.54362587],
       [ 1.78028121],
       [ 3.65868223],
       [ 3.19877697],
       [ 1.03072101],
       [ 4.245857  ],
       [ 2.00523751],
       [ 2.88001784],
       [-0.04972716],
       [ 3.74038955],
       [ 2.14183535],
       [ 2.66285617],
       [ 5.0323693 ],
       [ 2.61649898],
       [ 0.57146111],
       [ 3.43910842],
       [ 2.31987194],
       [ 1.19594332],
       [ 3.16015688],
       [ 3.75787435],
       [ 4.41037165],
       [ 3.29848976],
       [ 2.63644033],
       [ 2.36363924],
       [ 1.5752112 ],
       [ 4.98588534],
       [ 1.96452945],
       [ 3.48110924],
       [ 3.63634936],
       [ 3.24012803],
       [ 2.07775926],
       [ 0.70109891],
       [ 3.52007718],
       [ 1.7083216 ],
       [ 0.90698386],
       [ 1.61342237],
       [ 3.58821186],
       [ 3.55147905],
       [ 0.10625106],
       [ 2.94229457],
       [-1.42736093],
       [ 1.57135873],
       [ 4

Сформируем вектор-строку $\mathbf{q}^T$

In [40]:
q = np.array([n[24] * n[71]])
q

array([[16, 28, 20, 28, 16, 35, 16, 28, 20, 28, 16, 35, 16, 28, 20, 28,
        16, 35, 16, 28, 20, 28, 16, 35, 16, 28, 20, 28, 16, 35, 16, 28,
        20, 28, 16, 35, 16, 28, 20, 28, 16, 35, 16, 28, 20, 28, 16, 35,
        16, 28, 20, 28, 16, 35, 16, 28, 20, 28, 16, 35, 16, 28, 20, 28,
        16, 35, 16, 28, 20, 28, 16, 35, 16, 28, 20, 28, 16, 35, 16, 28,
        20, 28, 16, 35, 16]])

#### Вычисление значения функции $\mathbf{f}$ <a class="anchor" id="4"></a>

In [41]:
q_square = q ** 2
q_square

array([[ 256,  784,  400,  784,  256, 1225,  256,  784,  400,  784,  256,
        1225,  256,  784,  400,  784,  256, 1225,  256,  784,  400,  784,
         256, 1225,  256,  784,  400,  784,  256, 1225,  256,  784,  400,
         784,  256, 1225,  256,  784,  400,  784,  256, 1225,  256,  784,
         400,  784,  256, 1225,  256,  784,  400,  784,  256, 1225,  256,
         784,  400,  784,  256, 1225,  256,  784,  400,  784,  256, 1225,
         256,  784,  400,  784,  256, 1225,  256,  784,  400,  784,  256,
        1225,  256,  784,  400,  784,  256, 1225,  256]])

In [42]:
q_square_argmax = q_square.argmax()
q_square_argmax

5

In [43]:
f = 4 * n[q_square_argmax, 59]
f

28

#### Вычисление значения функции $\mathbf{g}$ <a class="anchor" id="5"></a>

In [44]:
m_dot_p = m.dot(p)
print(m_dot_p.shape)
print(m_dot_p)

(85, 1)
[[ 522.62731008]
 [ 536.54765933]
 [ 545.24503235]
 [ 524.52537963]
 [ 536.74252937]
 [ 560.96550301]
 [ 562.30409916]
 [ 536.18081365]
 [ 592.89956746]
 [ 558.81951122]
 [ 581.20037318]
 [ 519.57627386]
 [ 614.22973735]
 [ 578.54955288]
 [ 597.94282747]
 [ 676.72344692]
 [ 607.0644647 ]
 [ 540.72113741]
 [ 647.96700999]
 [ 611.19500422]
 [ 569.75367465]
 [ 656.60674421]
 [ 689.82434434]
 [ 728.00746623]
 [ 682.3459967 ]
 [ 655.17845514]
 [ 645.99287844]
 [ 607.35661431]
 [ 804.9154626 ]
 [ 636.62723621]
 [ 733.0676622 ]
 [ 749.81000796]
 [ 731.32832038]
 [ 659.92986864]
 [ 569.09582314]
 [ 770.64547807]
 [ 645.42747507]
 [ 588.74378787]
 [ 644.95352079]
 [ 804.1887355 ]
 [ 808.38980132]
 [ 529.53883646]
 [ 770.81503685]
 [ 396.53959744]
 [ 660.57092528]
 [ 955.86808279]
 [ 722.72258352]
 [ 912.83006712]
 [ 813.74808639]
 [ 465.11125632]
 [ 949.07400552]
 [1000.04384161]
 [ 763.54699765]
 [ 983.43479932]
 [ 888.1610762 ]
 [ 662.16920973]
 [1072.42592975]
 [ 632.95801783]
 [1150

In [45]:
m_dot_p_mul_q = m_dot_p * q
print(m_dot_p_mul_q.shape)
print(m_dot_p_mul_q)

(85, 85)
[[ 8362.03696125 14633.56468218 10452.54620156 ...  8362.03696125
  18291.95585273  8362.03696125]
 [ 8584.76254921 15023.33446112 10730.95318652 ...  8584.76254921
  18779.1680764   8584.76254921]
 [ 8723.92051757 15266.86090575 10904.90064697 ...  8723.92051757
  19083.57613219  8723.92051757]
 ...
 [10217.55351355 17880.71864871 12771.94189193 ... 10217.55351355
  22350.89831089 10217.55351355]
 [11664.97938184 20413.71391822 14581.2242273  ... 11664.97938184
  25517.14239778 11664.97938184]
 [23291.36661441 40759.89157521 29114.20826801 ... 23291.36661441
  50949.86446901 23291.36661441]]


In [46]:
m_dot_p_mul_q_mul_constant = m_dot_p_mul_q * 7e-6
m_dot_p_mul_q_mul_constant

array([[0.05853426, 0.10243495, 0.07316782, ..., 0.05853426, 0.12804369,
        0.05853426],
       [0.06009334, 0.10516334, 0.07511667, ..., 0.06009334, 0.13145418,
        0.06009334],
       [0.06106744, 0.10686803, 0.0763343 , ..., 0.06106744, 0.13358503,
        0.06106744],
       ...,
       [0.07152287, 0.12516503, 0.08940359, ..., 0.07152287, 0.15645629,
        0.07152287],
       [0.08165486, 0.142896  , 0.10206857, ..., 0.08165486, 0.17862   ,
        0.08165486],
       [0.16303957, 0.28531924, 0.20379946, ..., 0.16303957, 0.35664905,
        0.16303957]])

In [47]:
m_dot_p_mul_q_mul_constant_square = m_dot_p_mul_q_mul_constant ** 2
m_dot_p_mul_q_mul_constant_square

array([[0.00342626, 0.01049292, 0.00535353, ..., 0.00342626, 0.01639519,
        0.00342626],
       [0.00361121, 0.01105933, 0.00564251, ..., 0.00361121, 0.0172802 ,
        0.00361121],
       [0.00372923, 0.01142078, 0.00582693, ..., 0.00372923, 0.01784496,
        0.00372923],
       ...,
       [0.00511552, 0.01566628, 0.007993  , ..., 0.00511552, 0.02447857,
        0.00511552],
       [0.00666752, 0.02041927, 0.01041799, ..., 0.00666752, 0.0319051 ,
        0.00666752],
       [0.0265819 , 0.08140707, 0.04153422, ..., 0.0265819 , 0.12719855,
        0.0265819 ]])

In [48]:
submatrix = m_dot_p_mul_q_mul_constant_square[24:70,13:28]
print(submatrix.shape)
print(submatrix)

(46, 15)
[[0.01788634 0.00912568 0.01788634 0.00584044 0.0279474  0.00584044
  0.01788634 0.00912568 0.01788634 0.00584044 0.0279474  0.00584044
  0.01788634 0.00912568 0.01788634]
 [0.01649041 0.00841347 0.01649041 0.00538462 0.02576626 0.00538462
  0.01649041 0.00841347 0.01649041 0.00538462 0.02576626 0.00538462
  0.01649041 0.00841347 0.01649041]
 [0.01603126 0.00817921 0.01603126 0.0052347  0.02504884 0.0052347
  0.01603126 0.00817921 0.01603126 0.0052347  0.02504884 0.0052347
  0.01603126 0.00817921 0.01603126]
 [0.01417097 0.00723009 0.01417097 0.00462726 0.02214215 0.00462726
  0.01417097 0.00723009 0.01417097 0.00462726 0.02214215 0.00462726
  0.01417097 0.00723009 0.01417097]
 [0.0248893  0.01269862 0.0248893  0.00812712 0.03888953 0.00812712
  0.0248893  0.01269862 0.0248893  0.00812712 0.03888953 0.00812712
  0.0248893  0.01269862 0.0248893 ]
 [0.01556978 0.00794377 0.01556978 0.00508401 0.02432779 0.00508401
  0.01556978 0.00794377 0.01556978 0.00508401 0.02432779 0.005084

In [49]:
submatrix_row_elements_mul = submatrix.prod(axis=1)
print(submatrix_row_elements_mul.shape)
print(submatrix_row_elements_mul)

(46,)
[2.26146060e-29 6.68402121e-30 4.37604216e-30 6.87958994e-31
 3.21186809e-27 2.82361857e-30 1.94344138e-28 3.82636657e-28
 1.80976147e-28 8.30200791e-30 9.76813230e-32 8.70740254e-28
 4.26258502e-30 2.70420568e-31 4.16967424e-30 3.12600130e-27
 3.65489044e-27 1.12508179e-32 8.76506082e-28 1.91799040e-36
 8.54738417e-30 5.57427514e-25 1.26881516e-28 1.39941874e-25
 4.45603915e-27 2.29591124e-34 4.50040859e-25 2.16182623e-24
 6.59664029e-28 1.30802712e-24 6.15179247e-26 9.19007523e-30
 1.75901187e-23 2.37408769e-30 1.45602335e-22 4.47357187e-23
 2.33925855e-23 2.19567022e-28 2.58498106e-28 1.31805590e-20
 2.38559207e-22 1.42622267e-21 1.09694485e-22 1.34749384e-22
 1.28633348e-19 1.64747840e-24]


In [50]:
np.sum(submatrix_row_elements_mul)

1.4396079779214834e-19

### Выводы
В ходе данного задания в лабораторной работе была изучена библиотека NumPy, были получены навыки выполнения векторных вычислений с использованием вышеназванной библиотеки и найдены значения заданных выражений.